import { makeId } from './ids.js';
import { nowIso } from './time.js';

export function buildDefaultActionIntents({ runId, connectorBindingId }) {
  const bindingFragment = connectorBindingId
    ? { connector_binding_id: connectorBindingId }
    : {};

  return [
    {
      id: makeId('act'),
      run_id: runId,
      step_id: 'send_summary',
      ...bindingFragment,
      capability: 'message.send',
      side_effect: 'mutation',
      idempotency_key: `${runId}_send_summary_v1`,
      risk_hint: 'R2',
      parameters: {
        channel: 'ops-room',
        content: 'Weekly ops summary generated by FlockMesh runtime.'
      },
      target: {
        surface: 'office.chat'
      }
    }
  ];
}

export function runStatusFromDecisions(decisions) {
  if (decisions.some((d) => d.decision === 'deny')) return 'failed';
  if (decisions.some((d) => d.decision === 'escalate')) return 'waiting_approval';
  return 'running';
}

export function buildRunRecord({ workspaceId, agentId, playbookId, trigger }) {
  const id = makeId('run');

  return {
    id,
    workspace_id: workspaceId,
    agent_id: agentId,
    playbook_id: playbookId,
    trigger,
    status: 'accepted',
    revision: 1,
    action_intents: [],
    policy_decisions: [],
    approval_state: {},
    event_stream_ref: `event://runs/${id}`,
    audit_ledger_ref: `ledger://runs/${id}`,
    started_at: nowIso()
  };
}

export function buildExecutionResult({ actionIntent, deduped = false }) {
  return {
    action_intent_id: actionIntent.id,
    capability: actionIntent.capability,
    status: 'executed',
    deduped,
    executed_at: nowIso()
  };
}
